// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../twgl.js

import * as twgl from 'twgl.js';

type Vec3 = [number, number, number];
export interface KloudsOptions {
    selector: string | HTMLCanvasElement;
    speed?: number;
    layerCount?: number;
    bgColor?: Vec3;
    cloudColor1?: Vec3;
    cloudColor2?: Vec3;
}
export class Klouds {
    gl: WebGLRenderingContext;
    programInfo: twgl.ProgramInfo;
    bufferInfo: twgl.BufferInfo;
    arrays: {
        position: number[];
    };
    isRunning: boolean;
    accumTime: number;
    lastTime: number;
    speed: number;
    layerCount: number;
    bgColor: Vec3;
    cloudColor1: Vec3;
    cloudColor2: Vec3;
    constructor(options: KloudsOptions);
    render: (time: number) => void;
    stop(): void;
    start(): void;
    setCloudColor1(color: string | Vec3): void;
    setCloudColor2(color: string | Vec3): void;
    setBgColor(color: string | Vec3): void;
    setLayerCount(count: number): void;
}
export function create(options: KloudsOptions): Klouds;
export {};

