// Generated by dts-bundle v0.7.3

export type Vec3 = [number, number, number];
export const VERSION: string;
export interface KloudsOptions {
    selector: string | HTMLCanvasElement;
    speed?: number;
    layerCount?: number;
    bgColor?: Vec3;
    cloudColor1?: Vec3;
    cloudColor2?: Vec3;
}
export class Klouds {
    constructor(options: KloudsOptions);
    start(): void;
    stop(): void;
    setSpeed(speed: number): void;
    setCloudColor1(color: string | Vec3): void;
    setCloudColor2(color: string | Vec3): void;
    setBgColor(color: string | Vec3): void;
    setLayerCount(count: number): void;
    getSpeed(): number;
    getLayerCount(): number;
    getBgColor(): number[];
    getCloudColor1(): number[];
    getCloudColor2(): number[];
}
export function create(options: KloudsOptions): Klouds;

